[package]
authors = ["Me <Me>"]
edition = "2018"
name = "daggylp"
version = "0.1.0"

[dependencies]
dot = "0.1.4"
fnv = "*"
glob = "0.3.0"
grb = "1.0.4"
proptest = "1.0.0"
rand = { version = "0.8.3", features = ["small_rng"]}

[dev-dependencies]
test-case = "1.1.0"

[[bin]]
name = "generate-test-cases"
path = "src/bin/generate-test-cases.rs"
